#!/bin/bash

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. /etc/os-release

if [ ! -e "$1" ]; then
    echo "File '$1' does not exist." >&2
    exit 1
fi

md5=$( md5sum "$1" )

CM_VERSION=$2

if [[ "$CM_VERSION" =~ "trunk" ]]; then
    CM_VERSION=""
fi

if [ "$ID" == "ubuntu" ]; then
    echo cm"$CM_VERSION"-${md5:0:10}
else
    echo cm"$CM_VERSION"_${md5:0:10}
fi
