#!/bin/sh

# SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

# This script creates a new password for mysql user 'slurm',
# then updates database and slurmdbd.conf with new password.
# Unnecessary parameters:
# $1: slurmdbd.conf path,
# $2: number of symbols in new password (default: 16)
# $3: mysql root password
# $4: failover hostname or IP

LOGFILE=/tmp/slurm-restore-pass.log
SLURMDBD_CONF=/cm/shared/apps/slurm/etc/slurmdbd.conf
SLURMDBD_CONF_TEMPLATE=/cm/local/apps/slurm/current/templates/slurmdbd.conf.template

echo "MySQL password for user slurm will be regenerated."
echo

# slurmdbd.conf path
if [ -z "$1" ]; then
    echo -n "Specify slurmdbd.conf path and press <ENTER> [$SLURMDBD_CONF]: "
    read SLURMDBD_NEW 
    echo
    if [ -n "$SLURMDBD_NEW" ]; then
        if [ -f "$SLURMDBD_NEW" ]; then
            SLURMDBD_CONF=$SLURMDBD_NEW
        else
            echo "ERROR: no such file: $SLURMDBD_NEW"
            exit 1
        fi
    fi

    echo -n "Specify slurmdbd.conf template path and press <ENTER> [$SLURMDBD_CONF_TEMPLATE]: "
    read SLURMDBD_NEW_TEMPLATE
    echo
    if [ -n "$SLURMDBD_NEW_TEMPLATE" ]; then
        if [ -f "$SLURMDBD_NEW_TEMPLATE" ]; then 
            SLURMDBD_CONF_TEMPLATE=$SLURMDBD_NEW_TEMPLATE
        else
            echo "ERROR: no such file: $SLURMDBD_NEW_TEMPLATE"
            exit 1
        fi
    fi

    if [ ! -f "$SLURMDBD_CONF_TEMPLATE" ]; then
        echo "ERROR: no such file: $SLURMDBD_CONF_TEMPLATE"
        exit 1
    fi
else
    SLURMDBD_CONF="$1"
    SLURMDBD_CONF_TEMPLATE=$1.template
fi  

# Number of symbols in the new password
if [ "$2" ]; then
    num=$2
else
    num=16
fi

# Mysql root password
mpass=""
if [ "$3" ]; then
    mpass="$3"
else
    echo -n "Enter mysql root password and press <ENTER>: "
    stty -echo 
    read mpass;
    stty echo
    echo 
    if [ -z "$mpass" ]
    then 
        echo "You must enter mysql root password!"
        exit 1
    fi
    if ! mysql --defaults-extra-file=<( echo \"[client]\"; echo user=root; echo password=$mpass; ) -e ";" 2> /dev/null ; then
        echo "Wrong mysql root password, operation was aborted."
        exit 1
    fi
fi

echo "Generating new MySQL password for user slurm"
pass=$(</dev/urandom tr -dc A-Za-z0-9| (head -c $num))

echo "Updating local DB with new password ..."
{
	sh -c "echo 'CREATE USER IF NOT EXISTS \"slurm\"@\"%\";' | mysql <( echo \"[client]\"; echo user=root; echo password=$mpass; ) "
	sh -c "echo 'ALTER USER \"slurm\"@\"%\" IDENTIFIED BY \"$pass\";' | mysql <( echo \"[client]\"; echo user=root; echo password=$mpass; ) "
	sh -c "echo 'GRANT ALL PRIVILEGES ON slurm_acct_db.* TO \"slurm\"@\"%\" WITH GRANT OPTION;' | mysql <( echo \"[client]\"; echo user=root; echo password=$mpass; ) "
	sh -c "echo 'FLUSH PRIVILEGES;' | mysql <( echo \"[client]\"; echo user=root; echo password=$mpass; ) "
} 1>>$LOGFILE 2>&1
echo

# Number of symbols in the new password
failover=""
if [ "$4" ]; then
    failover="$4"
else
    echo -n "Enter failover node hostname or IP (or leave it blank if no failover node is used) and press <ENTER>: "
    read failover;
    echo 
fi

if [ -n "$failover" ]; then
    echo "Updating DB on $failover with new password ..." 
    ssh "$failover" "echo 'CREATE USER IF NOT EXISTS \"slurm\"@\"%\";' | mysql -u root -p\"$mpass\" 1>>$LOGFILE 2>&1"
    ssh "$failover" "echo 'ALTER USER \"slurm\"@\"%\" IDENTIFIED BY \"$pass\";' | mysql -u root -p\"$mpass\" 1>>$LOGFILE 2>&1"
    ssh "$failover" "echo 'GRANT ALL PRIVILEGES ON slurm_acct_db.* TO \"slurm\"@\"%\" WITH GRANT OPTION;' | mysql -u root -p\"$mpass\" 1>>$LOGFILE 2>&1"
    ssh "$failover" "echo 'FLUSH PRIVILEGES;' | mysql -u root -p\"$mpass\"  1>>$LOGFILE 2>&1"
    echo
fi

if [ -n "$SLURMDBD_CONF" ]; then
    if [ -f "$SLURMDBD_CONF" ]; then
        echo "Updating $SLURMDBD_CONF ..."
        sed -i "s/.*StoragePass.*/StoragePass=${pass}/g" "$SLURMDBD_CONF"
    else
        echo "Skip updating of $SLURMDBD_CONF (does not exist yet)"
    fi
    echo
fi

echo "Updating $SLURMDBD_CONF_TEMPLATE ..."
sed -i "s/.*StoragePass.*/StoragePass=${pass}/g" "$SLURMDBD_CONF_TEMPLATE"
echo

if [ -n "$failover" ]; then
    if ssh "$failover" test -f "$SLURMDBD_CONF_TEMPLATE"; then
        echo "Updating $SLURMDBD_CONF_TEMPLATE on $failover ..."
        ssh "$failover" sed -i "s/.*StoragePass.*/StoragePass=${pass}/g" "$SLURMDBD_CONF_TEMPLATE"
    else
        echo "$SLURMDBD_CONF_TEMPLATE does not exist yet on $failover"
    fi
fi

echo "Done."
