#
# See the slurm.conf man page for more information.
#

SlurmUser=slurm
#SlurmdUser=root
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
#DisableRootJobs=NO
#EnforcePartLimits=NO
#SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=pmix
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmdPidFile=/var/run/slurmd.pid
#PluginDir=
#FirstJobId=
ReturnToService=2
#GroupUpdateForce=0
#GroupUpdateTime=600
#JobFileAppend=0
#JobRequeue=1
#JobSubmitPlugins=lua
#KillOnBadExit=0
#LaunchType=launch/slurm
#Licenses=foo*4,bar
#MailProg=/bin/mail
#MaxJobCount=10000
#MaxStepCount=40000
#MaxTasksPerNode=512
#PlugStackConfig=
PrivateData=accounts,users,jobs,reservations
#PrologFlags=
#PropagatePrioProcess=0
#PropagateResourceLimits=ALL
#PropagateResourceLimitsExcept=
RebootProgram=reboot
#SrunProlog=
#SrunEpilog=
#TaskProlog=
#TaskEpilog=
TaskPlugin=task/cgroup
#TopologyPlugin=topology/tree
#TmpFS=/tmp
#TrackWCKey=no
#TreeWidth=50
#UnkillableStepProgram=
#UsePAM=
#
#
# TIMERS
#BatchStartTimeout=10
#CompleteWait=0
#EpilogMsgTime=2000
#GetEnvTimeout=2
#HealthCheckInterval=0
#HealthCheckProgram=
InactiveLimit=0
KillWait=30
#MessageTimeout=10
#ResvOverRun=0
MinJobAge=900
#OverTimeLimit=0
SlurmctldTimeout=120
SlurmdTimeout=300
#UnkillableStepTimeout=60
#VSizeFactor=0
Waittime=0
#
#
# SCHEDULING
#SchedulerTimeSlice=30
#
#
# JOB PRIORITY
#PriorityFlags=
#PriorityType=priority/basic
#PriorityDecayHalfLife=
#PriorityCalcPeriod=
#PriorityFavorSmall=
#PriorityMaxAge=
#PriorityUsageResetPeriod=
#PriorityWeightAge=
#PriorityWeightFairshare=
#PriorityWeightJobSize=
#PriorityWeightPartition=
#PriorityWeightQOS=
#
#
# LOGGING
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurmctld
SlurmdDebug=info
SlurmdLogFile=/var/log/slurmd
#SlurmSchedLogFile=
#SlurmSchedLogLevel=
#DebugFlags=
#JobCompHost=
#JobCompLoc=
#JobCompPass=
#JobCompPort=
#JobCompType=jobcomp/filetxt
#JobCompLoc=/cm/local/apps/slurm/var/spool/job_comp.log
#
#
# ACCOUNTING
#AccountingStorageEnforce=associations,limits,qos
#AccountingStorageHost=
#AccountingStoragePass=
#AccountingStoragePort=
JobAcctGatherType=jobacct_gather/linux
JobAcctGatherFrequency=30
AccountingStorageType=accounting_storage/slurmdbd
#JobContainerType=job_container/none


# This section of this file was automatically generated by cmd. Do not edit manually!
# BEGIN AUTOGENERATED SECTION -- DO NOT REMOVE
ClusterName=SLURM_CLUSTER
ControlMachine=SLURM_CONTROL_MACHINE
AccountingStorageHost=master
SchedulerType=sched/backfill
SlurmctldHost=master
PartitionName=defq Default=YES MaxTime=INFINITE State=UP
GresTypes=gpu,mic
Prolog=/cm/local/apps/cmd/scripts/prolog
Epilog=/cm/local/apps/cmd/scripts/epilog
StateSaveLocation=/cm/shared/apps/slurm/statesave/SLURM_CLUSTER
# END AUTOGENERATED SECTION   -- DO NOT REMOVE
